name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint code with Rubocop
        run: bin/rubocop -f github

      - name: Scan for security vulnerabilities in gems
        run: bin/bundler-audit

      - name: Scan for Rails security vulnerabilities
        run: bin/brakeman --no-pager

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: stockflow
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: stock_flow_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      POSTGRES_USER: stockflow
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_PORT: 5433
      POSTGRES_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install JS dependencies
        run: npm install

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec
